
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jun 15 21:47:36 CEST 2016
//----------------------------------------------------

package rs.ac.bg.etf.ppProject;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 42;
  public static final int RINDEX = 7;
  public static final int INCREMENT = 17;
  public static final int CONST = 32;
  public static final int IS_GREATER = 24;
  public static final int LPAREN = 4;
  public static final int SEMI = 11;
  public static final int MINUS = 9;
  public static final int DECREMENT = 18;
  public static final int STR_CONST = 43;
  public static final int IS_LESS = 23;
  public static final int RPAREN = 5;
  public static final int COMMA = 12;
  public static final int CLASS = 29;
  public static final int DIV = 15;
  public static final int PLUS = 8;
  public static final int IF = 34;
  public static final int IS_EQUAL = 28;
  public static final int DOT = 13;
  public static final int EOF = 0;
  public static final int RETURN = 21;
  public static final int EQUAL = 10;
  public static final int LOGICAL_OR = 38;
  public static final int NEW = 33;
  public static final int error = 1;
  public static final int MUL = 14;
  public static final int NUMBER = 40;
  public static final int IDENT = 41;
  public static final int BREAK = 36;
  public static final int VOID = 31;
  public static final int ELSE = 35;
  public static final int LBRACE = 2;
  public static final int IS_GREATER_EQUAL = 26;
  public static final int IS_DIFFERENT = 27;
  public static final int READ = 20;
  public static final int WHILE = 37;
  public static final int LOGICAL_AND = 39;
  public static final int IS_LESS_EQUAL = 25;
  public static final int RBRACE = 3;
  public static final int EXTENDS = 30;
  public static final int PROG = 19;
  public static final int BOOL_CONST = 44;
  public static final int PERCENTAGE = 16;
  public static final int LINDEX = 6;
  public static final int PRINT = 22;
}

